# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-todo.fullname" . }}
  namespace: my-todo
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: {{ include "my-todo.fullname" . }}
