apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/sayahaya20/monitoring/argo-apps
    targetRevision: main
    path: Argo-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true